# MOwNiT 
## Laboratorium
## Wybrane zagadnienia algebry liniowej, faktoryzacja
### Algebra liniowa w Julii
https://docs.julialang.org/en/v1.7/stdlib/LinearAlgebra/index.html


In [1]:
using(LinearAlgebra)

In [2]:
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::StridedMatrix{T}) where T in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\dense.jl:1302
[2] factorize(A::Adjoint) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\dense.jl:1376
[3] factorize(A::Transpose) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\dense.jl:1377
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\triangular.jl:2569
[5] factorize(A::Tridiagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\lu.jl:567
[6] factorize(D::Diagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\diagonal.jl:137
[7] factorize(A::Bidiagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\bidiag.jl:845
[8] factorize(S::SymTridiagonal) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\ldlt.jl:170
[9] factorize(A::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\SparseArrays\src\linalg.jl:1586
[10] factorize(A::Union{Hermitian{ComplexF64, var"#s859"}, Hermitian{Float64, var"#s859"}, Symmetric{Float64, var"#s859"}} where var"#s859"<:SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\SparseArrays\src\linalg.jl:1616
[11] factorize(A::Union{Hermitian{T, S}, Symmetric{T, S}} where {T, S}) in LinearAlgebra at C:\Users\kzaja\AppData\Local\Programs\Julia-1.7.2\share\julia\stdlib\v1.7\LinearAlgebra\src\symmetric.jl:641

In [3]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Matrix{Int64}:
 1  2  2

In [4]:
y1=[1 ;2 ;3]

3-element Vector{Int64}:
 1
 2
 3

In [5]:
transpose(x1)

3×1 transpose(::Matrix{Int64}) with eltype Int64:
 1
 2
 2

In [6]:
#iloczyn skalarny
dot(x1,y1)

11

 Długość wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [7]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Matrix{Float64}:
 0.201333  0.730256   0.874181
 0.962293  0.61645    0.253017
 0.591243  0.0279556  0.208219

In [8]:
#losujemy wektor x
x=rand(3)

3-element Vector{Float64}:
 0.6494978713049762
 0.46570721507453183
 0.48760751497651733

In [9]:
# wyliczamy b
b=A*x

3-element Vector{Float64}:
 0.897107931693224
 1.03546539325556
 0.49855914678814334

### Sposoby rozwiązania Ax=b

In [10]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Vector{Float64}:
 0.6494978713049763
 0.4657072150745318
 0.4876075149765174

In [11]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Vector{Float64}:
 0.6494978713049762
 0.4657072150745318
 0.48760751497651744

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


### Faktoryzacja LU

In [12]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64, Matrix{Float64}}
L factor:
3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.209222   1.0       0.0
 0.61441   -0.583416  1.0
U factor:
3×3 Matrix{Float64}:
 0.962293  0.61645   0.253017
 0.0       0.601281  0.821245
 0.0       0.0       0.531891

In [13]:
# Macierz L
Af.L

3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.209222   1.0       0.0
 0.61441   -0.583416  1.0

In [14]:
#Macierz U
Af.U

3×3 Matrix{Float64}:
 0.962293  0.61645   0.253017
 0.0       0.601281  0.821245
 0.0       0.0       0.531891

In [15]:
# wektor permulatacji wierszy 
Af.p

3-element Vector{Int64}:
 2
 1
 3

In [16]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64, Matrix{Float64}}
L factor:
3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.209222   1.0       0.0
 0.61441   -0.583416  1.0
U factor:
3×3 Matrix{Float64}:
 0.962293  0.61645   0.253017
 0.0       0.601281  0.821245
 0.0       0.0       0.531891

In [17]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Vector{Float64}:
 0.6494978713049762
 0.4657072150745318
 0.48760751497651744

In [18]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Vector{Float64}:
 0.46028506974417727
 0.8374221118633624
 0.020357928999785613

### Faktoryzacja QR


In [19]:
B=rand(10,5)

10×5 Matrix{Float64}:
 0.413965   0.00524901  0.963826   0.632963  0.329576
 0.455467   0.410653    0.138445   0.867344  0.391937
 0.0478521  0.342658    0.592005   0.166132  0.729935
 0.595275   0.568469    0.959588   0.846336  0.28413
 0.254104   0.322546    0.632214   0.60233   0.340109
 0.661588   0.314318    0.0998852  0.288977  0.85628
 0.0989537  0.882192    0.644475   0.905718  0.894542
 0.469139   0.264447    0.952984   0.67456   0.413944
 0.399162   0.942584    0.103219   0.294836  0.266671
 0.770202   0.662923    0.24402    0.311711  0.877025

In [20]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64, Matrix{Float64}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64, Matrix{Float64}}:
 -0.480545    0.212773   -0.308719   …  -0.467789    -0.290149   -0.111893
 -0.069026   -0.221479    0.128279       0.0388043    0.174901   -0.175904
 -0.295162   -0.255131   -0.222705      -0.0666513    0.380218   -0.308677
 -0.478432    0.244019    0.306051      -0.255056     0.0138046  -0.15605
 -0.31521     0.0489261   0.0368137     -0.0782618    0.645647    0.624244
 -0.0498008  -0.579262   -0.305746   …  -0.0182322    0.199475   -0.32256
 -0.321323   -0.35082     0.210526      -0.0130101   -0.400169    0.07429
 -0.47514     0.145961   -0.101646       0.837935    -0.0915234  -0.0504201
 -0.0514632  -0.146444    0.771172       0.00011523   0.11606    -0.246299
 -0.121663   -0.526568    0.0278857     -0.0375557   -0.319117    0.523885
R factor:
5×5 Matrix{Float64}:
 -2.00569  -1.29121  -1.05958   -1.01128   -1.68687
  0.0      -1.36722  -0.962833  -0.680804  -0.457807
  0.0       0

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

#### 1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [21]:
A=zeros(6,3) 

6×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [22]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Vector{Int64}:
 1
 2
 4
 4
 3
 0

In [23]:
A[:,1]=x.^2

6-element Vector{Int64}:
  1
  4
  9
 16
 25
 36

In [24]:
A[:,2]=x

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [25]:
A[:,3]=ones(6)

6-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [26]:
A

6×3 Matrix{Float64}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A 

In [27]:
 AF=factorize(A)

QRPivoted{Float64, Matrix{Float64}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64, Matrix{Float64}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Matrix{Float64}:
 -47.697  -9.24587  -1.90788
   0.0    -2.34816  -1.43091
   0.0     0.0       0.559017
permutation:
3-element Vector{Int64}:
 1
 2
 3

In [28]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Matrix{Float64}:
  1.0           0.0           1.66533e-16  …   2.77556e-17  -2.77556e-17
  0.0           1.0           5.55112e-17      8.32667e-17  -9.71445e-17
  1.66533e-16   5.55112e-17   1.0             -6.93889e-17  -2.77556e-17
 -2.08167e-17  -4.85723e-17  -7.97973e-17     -6.59195e-17  -3.1225e-17
  2.77556e-17   8.32667e-17  -6.93889e-17      1.0          -2.77556e-17
 -2.77556e-17  -9.71445e-17  -2.77556e-17  …  -2.77556e-17   1.0

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [29]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Vector{Float64}:
 -0.5714285714285724
  3.94285714285715
 -2.8000000000000145

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [30]:
A \ y

3-element Vector{Float64}:
 -0.5714285714285723
  3.9428571428571493
 -2.8000000000000136

In [31]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
fit(x,y, 2)

Polynomial(-2.8000000000000136 + 3.9428571428571493*x - 0.5714285714285723*x^2)

In [15]:
@which fit

LoadError: "fit" is not defined in module Main

### Zadania

In [18]:
ENV["COLUMNS"] = 100

100

### Wykorzystywane importy:

In [59]:
using LinearAlgebra
using Plots
using Statistics
using DataFrames
using CSV
using Printf
using Polynomials

#### Zadanie 1 (1pkt)
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

In [20]:
x = rand(1000)
A = rand(1000, 1000)

1000×1000 Matrix{Float64}:
 0.788629   0.333147   0.0481984  0.522106   …  0.220189   0.0435112   0.188875    0.730207
 0.471046   0.578151   0.709583   0.338884      0.989991   0.889979    0.778592    0.0682957
 0.329317   0.377308   0.339426   0.118304      0.122249   0.338603    0.764461    0.522668
 0.976029   0.353132   0.531671   0.900156      0.307162   0.203615    0.217228    0.8068
 0.936355   0.239926   0.23591    0.189156      0.833787   0.504067    0.710337    0.511516
 0.15105    0.472135   0.831559   0.325856   …  0.630176   0.0462225   0.264523    0.434431
 0.625435   0.772676   0.804979   0.95451       0.134284   0.434432    0.372751    0.335875
 0.778099   0.319824   0.599807   0.717908      0.637869   0.674478    0.998297    0.799212
 0.560664   0.421746   0.405401   0.132803      0.791535   0.842071    0.83084     0.515638
 0.242885   0.180293   0.819394   0.964021      0.236202   0.868522    0.243395    0.848679
 0.610286   0.151486   0.0112341  0.357083   …  0.3791

In [21]:
b = A * x

1000-element Vector{Float64}:
 253.80366878575873
 249.66531832874588
 260.1411050544734
 260.24585862681977
 258.2764994848483
 254.2920162550386
 252.11071272067483
 255.08184186829038
 257.16761465872173
 263.34518742391737
 247.14595773258688
 258.2049084218831
 246.9448708070962
   ⋮
 246.36927900533254
 253.99575457400474
 253.91948351445382
 262.9591771344516
 251.16761031082237
 246.79617098272192
 250.1238427035777
 258.56090863510065
 256.2180937152455
 250.98074792220004
 249.3506447203309
 257.24709713133313

In [22]:
get_result_quality(y) = reduce((o1, o2) -> o1 + abs(o2), y - x)

get_result_quality (generic function with 1 method)

In [23]:
time1 = []
time2 = []
time3 = []
q_res1 = []
q_res2 = []
q_res3 = []

Any[]

In [24]:
for i in 1:20
    append!(q_res1, get_result_quality(inv(A) * b))      # compilation
    append!(q_res2, get_result_quality(A \ b))           # compilation
    append!(q_res3, get_result_quality(factorize(A) \ b)) # compilation
    
    append!(time1, @elapsed (inv(A) * b))
    append!(time2, @elapsed (A \ b))
    append!(time3, @elapsed (factorize(A) \ b))
end

In [34]:
df = DataFrame(
    inverse_quality = q_res1,
    division_quality = q_res2,
    factorize_quality = q_res3,
    inverse_time = time1,
    division_time = time2,
    factorize_time = time3,
)

20×6 DataFrame
 Row │ inverse_quality  division_quality  factorize_quality  inverse_time  division_time  factoriz ⋯
     │ Any              Any               Any                Any           Any            Any      ⋯
─────┼──────────────────────────────────────────────────────────────────────────────────────────────
   1 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0206453     0.00912555     0.015204 ⋯
   2 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.019177      0.00773096     0.008470
   3 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0187287     0.00757284     0.007725
   4 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0225496     0.0103542      0.007465
   5 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0191145     0.00746502     0.007325 ⋯
   6 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0186567     0.00740182     0.007261
   7 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0185821     0.00790205     0.007270
   8 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0192917     0.00989596     0.007554
   9 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0185034     0.00738115     0.007475 ⋯
  10 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0186314     0.00737686     0.007289
  11 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0184035     0.0075145      0.007533
  12 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0185338     0.00908589     0.007368
  13 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0313523     0.0110558      0.009460 ⋯
  14 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0309145     0.0100722      0.014052
  15 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0323637     0.0140494      0.014148
  16 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.020539      0.016794       0.007350
  17 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0182941     0.0074443      0.007647 ⋯
  18 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0189934     0.00735947     0.007263
  19 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0182558     0.00763538     0.007345
  20 │ 2.48034e-9       8.30932e-10       8.30932e-10        0.0254522     0.0108687      0.007533
                                                                                    1 column omitted

In [38]:
result_df = combine(
    df,
    :inverse_time => mean => :inverse_mean_time,
    :division_time => mean => :division_time,
    :factorize_time => mean => :factorize_mean_time
)

1×3 DataFrame
 Row │ inverse_mean_time  division_time  factorize_mean_time 
     │ Float64            Float64        Float64             
─────┼───────────────────────────────────────────────────────
   1 │         0.0213491      0.0092043            0.0086374

#### Zadanie 2 (1pkt)
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

In [40]:
filename = "results.csv"

df = CSV.read(filename, delim=";", DataFrame)
rf = combine(
    groupby(df, :rep),
    "gsl" => mean,
    "gsl" => std,
    "better" => mean,
    "better" => std,
    "naive" => mean,
    "naive" => std
)

9×7 DataFrame
 Row │ rep    gsl_mean   gsl_std      better_mean  better_std   naive_mean  naive_std   
     │ Int64  Float64    Float64      Float64      Float64      Float64     Float64     
─────┼──────────────────────────────────────────────────────────────────────────────────
   1 │   100  0.0007115  2.47801e-5     0.0044901  0.00017191    0.003538   0.00015482
   2 │   150  0.0020371  3.421e-5       0.0133261  0.000107486   0.0105641  0.000140158
   3 │   200  0.0049279  8.89562e-5     0.0314471  0.000313478   0.0287062  0.000203274
   4 │   250  0.0095744  0.000151814    0.0611521  0.000448047   0.0553567  0.000567858
   5 │   300  0.0163468  0.000281024    0.104382   0.000786254   0.101328   0.00123124
   6 │   350  0.0258364  0.000194061    0.166991   0.000646983   0.165872   0.00307208
   7 │   400  0.0386743  0.000259816    0.250914   0.00331126    0.249307   0.00224613
   8 │   450  0.0552321  0.000310424    0.354636   0.00213787    0.34589    0.00347847
   9 │   500  0.0762577  0.000810262    0.487278   0.00365006    0.511725   0.00427824

**Rozwiązanie układu:**

In [41]:
A = zeros(9, 4)

9×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

**Punkty $(x, y)$:**

In [44]:
y_gsl = rf[:, 2]
y_better = rf[:, 4]
y_naive = rf[:, 6]
x = rf[:, 1]

9-element Vector{Int64}:
 100
 150
 200
 250
 300
 350
 400
 450
 500

In [47]:
A[:, 1] = x.^3
A[:, 2] = x.^2
A[:, 3] = x
A[:, 4] = ones(9)
A

9×4 Matrix{Float64}:
 1.0e6      10000.0  100.0  1.0
 3.375e6    22500.0  150.0  1.0
 8.0e6      40000.0  200.0  1.0
 1.5625e7   62500.0  250.0  1.0
 2.7e7      90000.0  300.0  1.0
 4.2875e7  122500.0  350.0  1.0
 6.4e7     160000.0  400.0  1.0
 9.1125e7  202500.0  450.0  1.0
 1.25e8    250000.0  500.0  1.0

In [48]:
AF = factorize(A)

QRPivoted{Float64, Matrix{Float64}}
Q factor:
9×9 LinearAlgebra.QRPackedQ{Float64, Matrix{Float64}}:
 -0.00568765  -0.118781   -0.561563   0.727387   …   0.0674281  -0.0577123  -0.185632  -0.276661
 -0.0191958   -0.228854   -0.522342  -0.0519562     -0.249654   -0.0981256   0.19839    0.6852
 -0.0455012   -0.338579   -0.355826  -0.358127       0.426542    0.510199    0.334855  -0.200074
 -0.0888695   -0.422353   -0.126549  -0.334004      -0.314288   -0.224694   -0.263395  -0.527304
 -0.153566    -0.454574    0.10096   -0.122468      -0.27675    -0.243579   -0.113343   0.142465
 -0.243858    -0.409639    0.262169   0.133602   …   0.680947   -0.316439   -0.158047   0.215683
 -0.364009    -0.261947    0.292546   0.291326      -0.28285     0.681327   -0.203173   0.129619
 -0.518287     0.0141055   0.12756    0.207825      -0.149802   -0.228168    0.73803   -0.222297
 -0.710956     0.44412    -0.297319  -0.259781       0.0984266  -0.0228082  -0.347685   0.0533681
R factor:
4×4 Matrix{Float6

Poszukiwanym rozwiązaniem jest: $$wsp=Rfactor \setminus Q^T y[1:n]$$

In [63]:
@printf("GSL:\n%s\\n", AF.R \ (Transpose(AF.Q) * y_gsl)[1:4])
@printf("\n\nBetter:\n%s\n", AF.R \ (Transpose(AF.Q) * y_better)[1:4])
@printf("\nNaive:\n%s", AF.R \ (Transpose(AF.Q) * y_naive)[1:4])

GSL:
[6.748861952861983e-10, -5.402753246753515e-8, 1.212963732563806e-5, -0.0007102634920635519]\n

Better:
[3.799618181818194e-9, 9.561545454544187e-8, -2.8736818181814397e-5, 0.002684399999999681]

Naive:
[6.093503703703711e-9, -1.6265797835497928e-6, 0.00034775794420394737, -0.023165250793651088]

In [64]:
@printf("GSL using fit:\n%s\n", fit(x, y_gsl, 3))
@printf("\n\nBetter using fit:\n%s\n", fit(x, y_better, 3))
@printf("\n\nNaive using fit:\n%s\n", fit(x, y_naive, 3))

GSL using fit:
-0.000710263 + 1.21296e-5*x - 5.40275e-8*x^2 + 6.74886e-10*x^3


Better using fit:
0.0026844 - 2.87368e-5*x + 9.56155e-8*x^2 + 3.79962e-9*x^3


Naive using fit:
-0.0231653 + 0.000347758*x - 1.62658e-6*x^2 + 6.0935e-9*x^3


#### Zadanie 3 (2 pkt)

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - np. zastosowania w uczeniu maszynowym

Ad. Rozwiązanie do zadania 3 jest przedstawione w oddzielnym pliku.